Migrating from React Router to NextJS for image optimization
utmgdsc/website pull request #41
Opened 2023-06-24 19:16 UTC by HerschaLo

I have finished the migration of the website's codebase (aside from deployment-related files) to use NextJS instead of the currently used React Router.

2023-06-24 19:57 UTC, logonoff requested changes
great job! i'd be happy to merge once the changes are made 😋 

i've started by fixing two of them for you :)

2023-06-24 19:57 UTC, logonoff commented on frontend/src/components/Team/Team.jsx
> +						picture={teamMember.picture === undefined ? DefaultUser : require("../../assets/website_proprietary/brock.png")}
still has the testing code

2023-06-24 19:57 UTC, logonoff commented on frontend/src/components/HeroHeader/HeroHeader.jsx
> +	console.log(text)
remove debug code

2023-06-24 19:57 UTC, logonoff commented on frontend/.firebaserc
need to keep this file

2023-06-24 19:57 UTC, logonoff commented on frontend/firebase.json
need to keep this file

2023-06-24 19:57 UTC, logonoff commented on frontend/package.json
> -		"react-parallax": "^3.5.1",
i'd like to keep the parallax effect if possible--here is a [potential solution i googled](https://www.reddit.com/r/nextjs/comments/10sk6p3/how_to_handle_simple_parallax_effects_while_also/); youre free to not use this one

2023-06-24 19:57 UTC, logonoff commented on frontend/src/pages/PageNotFound/index.jsx
should use the custom 404 page rather than the default nextjs one

2023-06-24 19:57 UTC, logonoff commented on frontend/package.json
> -		"react-parallax": "^3.5.1",
react-parallax also has a way to use [custom background elements](https://www.npmjs.com/package/react-parallax#custom-background-element) which could potentially be a nextjs image component

2023-06-24 19:57 UTC, logonoff commented on frontend/public/favicon.ico
should keep the custom favicon

2023-06-24 19:57 UTC, logonoff commented on frontend/public/index.html
> -<html lang="en">
nextjs generated static HTML doesnt appear to have the `lang` attribute which is [important for screenreaders](https://dequeuniversity.com/rules/axe/4.4/html-has-lang)

2023-06-24 19:57 UTC, logonoff commented on frontend/src/app/HomepageHero/index.jsx
> +import HeroImage from '../../assets/backgrounds/background.jpg';
need to put `.src` in the inline css for this component so that the background property still works

2023-06-24 19:57 UTC, logonoff requested changes
great job! i'd be happy to merge once the changes are made 😋 

i've started by fixing two of them for you :)

2023-06-24 20:19 UTC, hiimchrislim commented on frontend/src/app/page.jsx
Please use a better name for all files apart from just `page.jsx`

2023-06-24 20:20 UTC, ggggg requested changes

2023-06-24 20:20 UTC, ggggg commented on frontend/src/app/layout.jsx
> +	console.log(systemTheme)
debug

2023-06-24 20:20 UTC, ggggg commented on frontend/src/app/resources/page.jsx
> +	console.log(BannerImg)
debug

2023-06-24 20:20 UTC, ggggg commented on frontend/src/app/index.jsx
> +//import WitSchedule from './WIT-schedule';
delete commented out code

2023-06-24 20:20 UTC, ggggg commented on frontend/src/app/index.jsx
> +*/
delete commented out code

2023-06-24 20:20 UTC, ggggg commented on frontend/src/app/layout.jsx
> +//import PageNotFound from './pages/PageNotFound';
delete commented out code

2023-06-24 20:20 UTC, hiimchrislim commented on frontend/src/app/resources/page.jsx
> +	console.log(BannerImg)
Do a thorough check of log statements that should be removed.

2023-06-25 15:45 UTC, logonoff commented on frontend/src/components/SkeletonLoadedImage/SkeletonLoadedImage.jsx
> -					width: loaded ? undefined : '0',
this should be kept if possible otherwise there will be positioning issues with the skeleton (as seen with the team listing)

2023-06-25 15:46 UTC, logonoff commented on frontend/src/components/SkeletonLoadedImage/SkeletonLoadedImage.jsx
> -					width: loaded ? undefined : '0',
height too

2023-06-26 19:53 UTC, HerschaLo commented on frontend/src/app/page.jsx
Unfortunately I can't. NextJS requires you to name all files that correspond to a page for a route "page.js"/"page.jsx". 

https://nextjs.org/docs/app/building-your-application/routing/pages-and-layouts

2023-06-26 20:08 UTC, logonoff approved these changes
LGTM--however, some regressions: 
* `SkeletonLoadedImage` no longer loads the wordmark `assets/graphics/gdscwordmark.svg` in `HomepageHero`
* the menu bar buttons on the 404 page do not work

2023-06-26 20:31 UTC, hiimchrislim commented on frontend/src/app/page.jsx
I see. That's an interesting choice that NextJS took with this approach.
Makes sense, thanks.

2023-06-26 20:34 UTC, hiimchrislim approved these changes
Leaving the review in the hands of the others.

2023-06-26 20:54 UTC, huonggiangbui reviewed
Some changes need to be done:
- Add EOF newline to some files
- Make sure tabs/spaces in files are consistent
- Be aware of some styling changes
- Suggestions of some good nextjs link 

@logonoff or @ggggg can you help with some formatting issues? 

Also thank you guys for all this!

2023-06-26 20:54 UTC, huonggiangbui commented on frontend/.dockerignore
Add EOF newline

2023-06-26 20:54 UTC, huonggiangbui commented on frontend/.firebaserc
Add EOF newline

2023-06-26 20:54 UTC, huonggiangbui commented on frontend/next.config.js
Add EOF newline

2023-06-26 20:54 UTC, huonggiangbui commented on frontend/src/app/not-found.jsx
Add EOF newline

2023-06-26 20:54 UTC, huonggiangbui commented on frontend/firebase.json
Add EOF newline

2023-06-26 20:54 UTC, huonggiangbui commented on frontend/src/components/SkeletonLoadedImage/SkeletonLoadedImage.jsx
> +				zIndex:-1,
I'm a bit cautious with those styles changes. Is there a reason why we should change this?

2023-06-26 20:54 UTC, huonggiangbui commented on frontend/src/components/EventList/EventList.jsx
> +					None yet! Check back soon, or check out our <NextLink href="/events#past-events">past events</NextLink>! 🤗
Good practice for next link (for SEO) is to use `Link` component from `next/link`, and inside it using `<a></a>`. For example:
```
<Link>
	<a>...</a>
</Link>
```

2023-06-26 20:54 UTC, huonggiangbui commented on frontend/src/app/page.jsx
> +				<HeroHeader text="Who are we?" picture={HeroInfoSesh} maxWidth="md" position="top"/>
I'm a bit cautious with those styles changes. Is there a reason why we should change this?

2023-06-26 20:54 UTC, huonggiangbui commented on frontend/src/app/layout.jsx
Add EOF newline

2023-06-26 21:28 UTC, logonoff commented on frontend/src/components/EventList/EventList.jsx
> +					None yet! Check back soon, or check out our <NextLink href="/events#past-events">past events</NextLink>! 🤗
[no longer needed since next 12.2](https://nextjs.org/blog/next-12-2#:~:text=next/link%20no%20longer%20requires%20manually%20adding%20%3Ca%3E%20as%20a%20child.%20You%20can%20now%20opt%20into%20this%20behavior%20in%20a%20backward%2Dcompatible%20way.), we are using next 13.4.3

2023-06-27 00:00 UTC, HerschaLo commented on frontend/src/app/page.jsx
> +				<HeroHeader text="Who are we?" picture={HeroInfoSesh} maxWidth="md" position="top"/>
This was added due to its necessity for manually implementing the parallax effect without using react-parallax (can't use NextJS Image component with it). Basically it was added to specify in the component that the parallax should start at the top of the source image.

2023-06-27 00:02 UTC, HerschaLo commented on frontend/src/components/SkeletonLoadedImage/SkeletonLoadedImage.jsx
> +				zIndex:-1,
This was done because the previous implementation caused cumulative layout shift when used in conjunction with NextJS' Image component. Thus, instead of deloading the Skeleton component, the image is now simply placed on top of it instead. A z-index value of -1 for the Skeleton component makes this possible.

2023-06-27 00:17 UTC, merged