Added pagination to events and projects pages
utmgdsc/website pull request #58
Opened 2023-07-11 16:23 UTC by JwuCode

Added pagination by filtering by year and added dates to projects through github api and stored in localstorage

2023-07-11 16:28 UTC, JwuCode commented
also commented out sustainazon because the url wasn't valid and I couldn't find it

2023-07-11 18:08 UTC, logonoff approved these changes
small changes are required but otherwise lgtm

2023-07-11 18:08 UTC, logonoff commented on src/data/projects.js
>  		"url": "https://github.com/utmgdsc/Sustainazon",
link has been fixed

2023-07-11 18:08 UTC, logonoff commented on src/components/EventList/EventList.jsx
> +		<div>
use react.fragment instead of div to the complexity of the dom

2023-07-11 18:08 UTC, logonoff commented on src/components/EventList/EventList.jsx
> +			<div>
use react.fragment (`<></>`) instead of div to the complexity of the dom

2023-07-11 18:08 UTC, logonoff commented on src/app/projects/page.jsx
> +	function getTerm(date) {
add jsdoc

2023-07-11 18:08 UTC, logonoff commented on src/app/projects/page.jsx
> +	const getProjectInfo = async () => {
add jsoc

2023-07-11 18:08 UTC, logonoff commented on src/app/projects/page.jsx
> +	const filteredProjects = (
add jsdoc

2023-07-11 18:08 UTC, logonoff commented on src/app/projects/page.jsx
> +		if ((!localStorage.getItem('time_stamp')) || (((localStorage.getItem('time_stamp') - new Date()) / 3600000) > 1)) {
explain what `3600000` means as a comment

2023-07-11 18:08 UTC, logonoff commented on src/app/projects/page.jsx
> +				await fetch('https://api.github.com/repos/utmgdsc/' + project.url.slice(27) + '/commits')
you cannot assume that the project author is `utmgdsc`. there may be github repos owned by other accounts (e.g., https://github.com/DSC-UTMap/utmap-website)

2023-07-11 18:08 UTC, logonoff commented on src/app/projects/page.jsx
> +				await fetch('https://api.github.com/repos/utmgdsc/' + project.url.slice(27) + '/commits')
you also cannot assume that every repo will have a github link

2023-07-11 18:08 UTC, logonoff commented on src/components/EventList/EventList.jsx
> +
formatting: fix whitespace

2023-07-11 18:08 UTC, logonoff commented on src/app/projects/page.jsx
> +
fix whitespace here

2023-07-11 19:27 UTC, huonggiangbui reviewed
Added comments. Also, I would prefer to have the pagination in the project/event page being "Fall 2022, Winter 2021, etc" rather than "1,2,3" (which is meaningless)

2023-07-11 19:27 UTC, huonggiangbui commented on src/data/projects.js
>  		"url": "https://github.com/utmgdsc/Sustainazon",
?

2023-07-11 19:27 UTC, huonggiangbui commented on src/components/EventList/EventList.jsx
> +			<Pagination count={currYear - 2019} onChange={(e, val) => { setPage(currYear + 1 - val) }} />
Consider refactoring, as code climate suggested

2023-07-11 19:27 UTC, huonggiangbui commented on src/components/EventList/EventList.jsx
> +			<div>
Agree

2023-07-11 19:27 UTC, huonggiangbui commented on src/components/EventList/EventList.jsx
> +	useEffect,
Shouldn't fix spacing

2023-07-11 19:27 UTC, huonggiangbui commented on src/app/projects/page.jsx
> +				await fetch('https://api.github.com/repos/utmgdsc/' + project.url.slice(27) + '/commits')
True. It's also not a good practice to count the date based on commit timestamp. I would prefer to add a new key (Date/Term) to project.json data

2023-07-11 19:29 UTC, huonggiangbui requested changes
^ See comments above

2023-07-12 06:09 UTC, logonoff commented on src/data/projects.js
>  		"url": "https://github.com/utmgdsc/Sustainazon",
repo was private, it is now public, hence the project can be uncommented

2023-07-26 18:54 UTC, JwuCode commented on src/data/projects.js
>  		"url": "https://github.com/utmgdsc/Sustainazon",
uncommented

2023-07-26 18:54 UTC, JwuCode commented on src/components/EventList/EventList.jsx
> +		<div>
added react.fragment

2023-07-26 18:55 UTC, JwuCode commented on src/components/EventList/EventList.jsx
> +			<div>
added react.fragment

2023-07-31 04:54 UTC, logonoff commented on src/components/EventList/EventList.jsx
> +
we'll just prettify this after merge

2023-07-31 04:54 UTC, logonoff commented on src/app/projects/page.jsx
> +
we'll just prettify this after merge

2023-07-31 04:55 UTC, logonoff commented on src/components/EventList/EventList.jsx
> +	useEffect,
this is fine as long as there are no conflicts

2023-08-12 10:28 UTC, logonoff commented on src/components/ProjectList/ProjectList.jsx
> +					await fetch('https://api.github.com/repos/' + project.url.slice(19) + '/commits')
where did 19 come from?

2023-08-12 15:00 UTC, JwuCode commented on src/components/ProjectList/ProjectList.jsx
> +					await fetch('https://api.github.com/repos/' + project.url.slice(19) + '/commits')
It takes the "utmgdsc/PollVotingSystem" from https://github.com/utmgdsc/PollVotingSystem

2023-08-12 18:53 UTC, huonggiangbui approved these changes
Looks awesome !! Thank you so much !!

2023-08-12 18:53 UTC, merged