Setting up Prettier and ESLint with pre-commit hook
utmgdsc/website pull request #8
Opened 2023-01-26 07:13 UTC by Rishav1707

## This PR closes the following issue:
closes #5

2023-01-30 06:37 UTC, huonggiangbui requested changes
looks good! one thing -- can you remove typescript and its related packages, since we don't really use it? then i think it's good to go!

2023-01-30 10:06 UTC, Rishav1707 commented
> looks good! one thing -- can you remove typescript and its related packages, since we don't really use it? then i think it's good to go!

![rm](https://user-images.githubusercontent.com/97666287/215447340-8bd93a2f-46fb-4a02-b3c0-dc99d979d240.png)

2023-01-31 02:50 UTC, logonoff requested changes

2023-01-31 02:50 UTC, logonoff commented on frontend/.eslintrc.js
> +    'standard-with-typescript'
typescript isn't used in our project

2023-01-31 02:51 UTC, logonoff commented
typescript is mentioned in package.json and other files when it is not used in the project

> > looks good! one thing -- can you remove typescript and its related packages, since we don't really use it? then i think it's good to go!
> 
> ![rm](https://user-images.githubusercontent.com/97666287/215447340-8bd93a2f-46fb-4a02-b3c0-dc99d979d240.png)

2023-01-31 20:12 UTC, merged